// src/desktop/src/components/auth/TurnstileWidget.vue
<script setup lang="ts">
/**
 * 人机验证挂件（provider 可切换：Cloudflare Turnstile / 自建滑块）
 *
 * 为什么是组件、而不是往发码按钮旁边插一个 div：
 *  1) 挂件要占一整行。`form-row` 是 flex 且验证码输入框 flex:1，
 *     把挂件塞进去会把输入框挤成一条缝（用户实测的「排版离谱」就是这个）；
 *  2) 登录页 / 注册页是两个 v-if 分支，按 id 找单个按钮只挂得到其中一个，
 *     另一个分支的「发送验证码」在开关打开后会 400（缺 token）。
 * 所以每个发码行各自挂一个实例，各自往上抛 payload。
 *
 * 两个 provider 的差别（服务端 /api/auth/captcha-config 的 provider 字段决定）：
 *  - turnstile：注入官方脚本 → turnstile.render → 抛 { turnstileToken }
 *  - self     ：GET /api/auth/captcha-challenge 取「背景图 + 滑块图 + 签名 token」
 *               → 用户拖动滑块 → 抛 { captchaToken, captchaX, captchaTrack }
 *               （缺口坐标**只在服务端签名 token 里**，前端拿到的是像素图 ⇒ 脚本要过就得做图像识别）
 *
 * 未启用时（provider=off / 凭据不齐 / 拉不到脚本）什么都不渲染、不发 payload，行为与接入前一致。
 */
import { onBeforeUnmount, onMounted, ref } from 'vue'
import { api } from '@/api/client'

const emit = defineEmits<{
  /** 交给父组件原样塞进发码请求体（未通过时为空对象） */
  payload: [payload: Record<string, unknown>]
  /** 服务端是否要求人机验证（父组件据此在发码前提示，而不是发一个注定 400 的请求） */
  enabled: [enabled: boolean]
}>()

const host = ref<HTMLElement | null>(null)
let widgetId = ''
let disposed = false

const SCRIPT_SRC = 'https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit'

interface TurnstileApi {
  render: (el: HTMLElement, options: Record<string, unknown>) => string
  remove?: (id: string) => void
}

function turnstileApi(): TurnstileApi | undefined {
  return (window as unknown as { turnstile?: TurnstileApi }).turnstile
}

/** 只注入一次脚本（显式渲染模式）；拉不到就 resolve 当未启用，绝不能把发码卡死 */
function loadScriptOnce(): Promise<void> {
  if (document.querySelector('script[data-clipsync-turnstile]')) return Promise.resolve()
  return new Promise((resolve) => {
    const s = document.createElement('script')
    s.src = SCRIPT_SRC
    s.async = true
    s.defer = true
    s.setAttribute('data-clipsync-turnstile', '1')
    s.onload = () => resolve()
    s.onerror = () => resolve()
    document.head.appendChild(s)
  })
}

// ───────────────────────── 自建滑块 ─────────────────────────
const bg = ref('')
const piece = ref('')
const pieceSize = ref(44)
const pieceY = ref(0)
const offsetX = ref(0) // 滑块当前左偏移
const dragging = ref(false)
const done = ref(false)

let challengeToken = ''
let startX = 0
let startOffset = 0
let trackPoints = 0
let trackStartAt = 0
let maxOffset = 0

async function loadChallenge() {
  try {
    const res = await api<{
      token?: string
      background?: string
      piece?: string
      y?: number
      pieceSize?: number
    }>('GET', '/api/auth/captcha-challenge')
    if (disposed || !res.ok || !res.data?.background || !res.data?.token) return
    bg.value = res.data.background
    piece.value = res.data.piece || ''
    pieceY.value = Number(res.data.y) || 0
    pieceSize.value = Number(res.data.pieceSize) || 44
    challengeToken = res.data.token
    offsetX.value = 0
    done.value = false
    // 背景宽度即最大可拖距离（背景图与容器同宽）
    maxOffset = Math.max(0, (host.value?.clientWidth || 300) - pieceSize.value)
  } catch {
    /* 出题失败按未启用处理：不拦发码（服务端未启用时门控也放行） */
  }
}

function onPointerDown(e: PointerEvent) {
  if (done.value || !bg.value) return
  dragging.value = true
  startX = e.clientX
  startOffset = offsetX.value
  trackPoints = 1
  trackStartAt = Date.now()
  ;(e.target as HTMLElement).setPointerCapture?.(e.pointerId)
}

function onPointerMove(e: PointerEvent) {
  if (!dragging.value) return
  const dx = e.clientX - startX
  offsetX.value = Math.min(Math.max(startOffset + dx, 0), maxOffset)
  trackPoints += 1
}

function onPointerUp() {
  if (!dragging.value) return
  dragging.value = false
  done.value = true
  // 立刻给"已拖动"的视觉反馈；真正的判定在服务端（缺口坐标只有它有）
  emit('payload', {
    captchaToken: challengeToken,
    captchaX: Math.round(offsetX.value),
    captchaTrack: { points: trackPoints, durationMs: Date.now() - trackStartAt },
  })
}

function reset() {
  emit('payload', {})
  void loadChallenge()
}

// ───────────────────────── 挂载 ─────────────────────────
onMounted(async () => {
  try {
    const res = await api<{ provider?: string; enabled?: boolean; siteKey?: string }>(
      'GET',
      '/api/auth/captcha-config'
    )
    if (disposed || !res.ok || !res.data?.enabled) return
    emit('enabled', true)

    const provider = res.data.provider || (res.data.siteKey ? 'turnstile' : 'off')

    if (provider === 'self') {
      await loadChallenge()
      return
    }

    if (!res.data.siteKey) return
    await loadScriptOnce()
    const el = host.value
    const w = turnstileApi()
    if (disposed || !el || !w || widgetId) return
    widgetId = w.render(el, {
      sitekey: res.data.siteKey,
      callback: (token: string) => emit('payload', { turnstileToken: token }),
      'expired-callback': () => emit('payload', {}),
      'error-callback': () => emit('payload', {}),
    })
  } catch {
    /* 任何异常都按未启用处理：服务端未启用时门控也放行 */
  }
})

onBeforeUnmount(() => {
  disposed = true
  const id = widgetId
  widgetId = ''
  if (id) {
    try {
      turnstileApi()?.remove?.(id)
    } catch {
      /* 卸载失败无所谓：父组件不再读它的 token */
    }
  }
})
</script>

<template>
  <div class="captcha-host">
    <!-- Turnstile 容器（provider=turnstile 时才由脚本填充） -->
    <div ref="host" />

    <!-- 自建滑块 -->
    <div v-if="bg" class="slider-wrap">
      <div class="slider-bg">
        <img :src="bg" alt="拖动滑块完成验证" draggable="false" />
        <img
          v-if="piece"
          class="slider-piece"
          :class="{ dragging, done }"
          :src="piece"
          :style="{ left: offsetX + 'px', top: pieceY + 'px', width: pieceSize + 'px', height: pieceSize + 'px' }"
          draggable="false"
          @pointerdown="onPointerDown"
          @pointermove="onPointerMove"
          @pointerup="onPointerUp"
          @pointercancel="onPointerUp"
        />
      </div>
      <div class="slider-bar">
        <span v-if="!done" class="slider-hint">按住滑块拖到缺口处</span>
        <span v-else class="slider-ok">
          已拖动，正在提交验证
          <button type="button" class="slider-reset" @click="reset">重来</button>
        </span>
      </div>
    </div>
  </div>
</template>

<style scoped>
/* 独占一行，不参与上面的 flex 行，也不撑宽输入框 */
.captcha-host {
  margin-top: 10px;
}
.slider-bg {
  position: relative;
  width: 300px;
  max-width: 100%;
  user-select: none;
  touch-action: none;
}
.slider-bg img {
  display: block;
  width: 100%;
  border-radius: 6px;
}
.slider-piece {
  position: absolute;
  cursor: grab;
  border-radius: 6px;
  box-shadow: 0 0 0 2px rgba(255, 255, 255, 0.85);
  transition: left 60ms linear;
}
.slider-piece.dragging {
  cursor: grabbing;
  transition: none;
}
.slider-piece.done {
  box-shadow: 0 0 0 2px var(--success, #16a34a);
}
.slider-bar {
  margin-top: 6px;
  font-size: 12px;
  color: var(--text-secondary, #666);
  display: flex;
  align-items: center;
  gap: 8px;
}
.slider-reset {
  background: none;
  border: none;
  color: var(--accent, #4f46e5);
  cursor: pointer;
  font-size: 12px;
  padding: 0;
}
</style>

// src/admin-console/src/components/TurnstileWidget/index.tsx
import { useCallback, useEffect, useRef, useState } from 'react';
import { fetchCaptchaConfig } from '@/api/auth';
import styles from './TurnstileWidget.module.css';

/**
 * 人机验证状态。
 * - `enabled=true` 表示服务端要求验证（此时 `payload` 为空就不能发码）
 * - `payload` 是**原样塞进发码请求体**的字段：
 *     turnstile ⇒ { turnstileToken }
 *     self（自建滑块）⇒ { captchaToken, captchaX, captchaTrack }
 */
export interface CaptchaState {
  enabled: boolean;
  payload: Record<string, unknown>;
}

interface TurnstileWidgetProps {
  onChange: (state: CaptchaState) => void;
}

const SCRIPT_SRC = 'https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit';

interface TurnstileApi {
  render: (el: HTMLElement, options: Record<string, unknown>) => string;
  remove?: (widgetId: string) => void;
}

function turnstileApi(): TurnstileApi | undefined {
  return (window as unknown as { turnstile?: TurnstileApi }).turnstile;
}

/** 只注入一次脚本（显式渲染模式）；拉不到就 resolve 当未启用，绝不能把登录页卡死 */
function loadScriptOnce(): Promise<void> {
  if (document.querySelector('script[data-clipsync-turnstile]')) return Promise.resolve();
  return new Promise((resolve) => {
    const s = document.createElement('script');
    s.src = SCRIPT_SRC;
    s.async = true;
    s.defer = true;
    s.setAttribute('data-clipsync-turnstile', '1');
    s.onload = () => resolve();
    s.onerror = () => resolve();
    document.head.appendChild(s);
  });
}

interface SliderChallenge {
  token: string;
  background: string;
  piece: string;
  y: number;
  pieceSize: number;
}

/** 取自建滑块题目。用原生 fetch + 相对路径：旁路信息不走 client 拦截器（免得弹无关 toast） */
async function fetchSliderChallenge(): Promise<SliderChallenge | null> {
  try {
    const resp = await fetch('/api/auth/captcha-challenge', { credentials: 'include' });
    if (!resp.ok) return null;
    const body = (await resp.json()) as { data?: SliderChallenge };
    return body.data?.token && body.data?.background ? body.data : null;
  } catch {
    return null;
  }
}

/**
 * 人机验证挂件（管理台登录页发码用）· provider 可切换。
 *
 * `GET /api/auth/captcha-config` 给出 provider：
 *  - turnstile：注入官方脚本 → turnstile.render（未配置 siteKey 则不渲染）
 *  - self     ：GET /api/auth/captcha-challenge 取「背景图 + 滑块图 + 签名 token」
 *                → 用户拖动滑块 → onChange({ enabled:true, payload:{ captchaToken, captchaX, captchaTrack } })
 * 未启用（默认）时**不渲染任何东西**，发码行为与接入前完全一致。
 */
export function TurnstileWidget({ onChange }: TurnstileWidgetProps) {
  const boxRef = useRef<HTMLDivElement | null>(null);
  const widgetIdRef = useRef<string>('');
  // 回调放 ref：父组件每次渲染都传新函数，进依赖数组会把挂件反复卸载重建
  const onChangeRef = useRef(onChange);
  onChangeRef.current = onChange;

  const [challenge, setChallenge] = useState<SliderChallenge | null>(null);
  const [offsetX, setOffsetX] = useState(0);
  const [dragging, setDragging] = useState(false);
  const [done, setDone] = useState(false);
  const dragRef = useRef({ startX: 0, startOffset: 0, points: 0, startedAt: 0, max: 260 });
  const bgRef = useRef<HTMLDivElement | null>(null);

  const loadChallenge = useCallback(async () => {
    const c = await fetchSliderChallenge();
    if (!c) return;
    setChallenge(c);
    setOffsetX(0);
    setDone(false);
    const w = bgRef.current?.clientWidth ?? 300;
    dragRef.current.max = Math.max(0, w - (c.pieceSize || 44));
  }, []);

  useEffect(() => {
    let cancelled = false;
    void (async () => {
      const cfg = await fetchCaptchaConfig();
      if (cancelled || !cfg.enabled) return;
      onChangeRef.current({ enabled: true, payload: {} });

      if (cfg.provider === 'self') {
        await loadChallenge();
        return;
      }
      if (!cfg.siteKey) return;
      await loadScriptOnce();
      const el = boxRef.current;
      const api = turnstileApi();
      // StrictMode 下 effect 会跑两遍：widgetIdRef 就是「已渲染过」的哨兵
      if (cancelled || !el || !api || widgetIdRef.current) return;
      widgetIdRef.current = api.render(el, {
        sitekey: cfg.siteKey,
        callback: (token: string) => onChangeRef.current({ enabled: true, payload: { turnstileToken: token } }),
        'expired-callback': () => onChangeRef.current({ enabled: true, payload: {} }),
        'error-callback': () => onChangeRef.current({ enabled: true, payload: {} }),
      });
    })();
    return () => {
      cancelled = true;
      const id = widgetIdRef.current;
      widgetIdRef.current = '';
      if (id) {
        try {
          turnstileApi()?.remove?.(id);
        } catch {
          /* 卸载失败无所谓：父组件不再读它的 token */
        }
      }
    };
    // loadChallenge 稳定（useCallback 无依赖）
  }, [loadChallenge]);

  const onPointerDown = (e: React.PointerEvent<HTMLImageElement>) => {
    if (!challenge || done) return;
    setDragging(true);
    dragRef.current.startX = e.clientX;
    dragRef.current.startOffset = offsetX;
    dragRef.current.points = 1;
    dragRef.current.startedAt = Date.now();
    try {
      (e.target as HTMLElement).setPointerCapture(e.pointerId);
    } catch {
      /* 捕获失败也能靠 move 事件拖动 */
    }
  };

  const onPointerMove = (e: React.PointerEvent<HTMLImageElement>) => {
    if (!dragging) return;
    const dx = e.clientX - dragRef.current.startX;
    const next = Math.min(Math.max(dragRef.current.startOffset + dx, 0), dragRef.current.max);
    setOffsetX(next);
    dragRef.current.points += 1;
  };

  const onPointerUp = () => {
    if (!dragging || !challenge) return;
    setDragging(false);
    setDone(true);
    // 立刻给"已拖动"的视觉反馈；真正判定在服务端（缺口坐标只有它有）
    onChangeRef.current({
      enabled: true,
      payload: {
        captchaToken: challenge.token,
        captchaX: Math.round(offsetX),
        captchaTrack: { points: dragRef.current.points, durationMs: Date.now() - dragRef.current.startedAt },
      },
    });
  };

  if (!challenge) {
    // Turnstile（或无验证）路径：只留官方挂件容器
    return <div ref={boxRef} className={styles.box} />;
  }

  return (
    <div className={styles.sliderWrap}>
      <div ref={bgRef} className={styles.sliderBg}>
        <img src={challenge.background} alt="拖动滑块完成验证" draggable={false} />
        {challenge.piece ? (
          <img
            className={styles.sliderPiece}
            data-done={done ? '1' : '0'}
            src={challenge.piece}
            draggable={false}
            style={{
              left: offsetX,
              top: challenge.y,
              width: challenge.pieceSize,
              height: challenge.pieceSize,
              cursor: dragging ? 'grabbing' : 'grab',
            }}
            onPointerDown={onPointerDown}
            onPointerMove={onPointerMove}
            onPointerUp={onPointerUp}
            onPointerCancel={onPointerUp}
          />
        ) : null}
      </div>
      <div className={styles.sliderBar}>
        {done ? (
          <>
            已拖动，正在提交验证
            <button
              type="button"
              className={styles.sliderReset}
              onClick={() => {
                onChangeRef.current({ enabled: true, payload: {} });
                void loadChallenge();
              }}
            >
              重来
            </button>
          </>
        ) : (
          '按住滑块拖到缺口处'
        )}
      </div>
    </div>
  );
}
